### ISSUE TITLE
Error after one comment

### ISSUE THREAD

**Issue by fmchan** [Fytex/Instagram-Giveaways-Winner#1]
lambda x: x.find_element_by_css_selector('article[role=\'presentation\'] form > button[disabled]'))
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\support\wait.py", line 96, in until_not
    raise TimeoutException(message)
selenium.common.exceptions.TimeoutException: Message:

**Comment by Fytex** [comment]
Hi,
I made a temporary fix. I'll test it later. 
Appreciate some feedback if you are available. 
Thanks for your help.

**Comment by fmchan** [comment]
> Hi,
> I made a temporary fix. I'll test it later.
> Appreciate some feedback if you are available.
> Thanks for your help.

awesome, I will try it. i also did a temporary fix by adding try catch TimeoutException

**Comment by Fytex** [comment]
I'll close this issue since I tested and seemed to work out.
Thanks for your help :)
