### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by theodoroslam** [Fytex/Instagram-Giveaways-Winner#14]
Hi there wonderful script but i am facing a problem and i hope you can help me.
I want the script to go to a post and tag 2 accounts continuously.
I edited the config file and it works only if i put the accounts i want to be tagged with a "\" in front of the "@"
So if i write the accounts like this "\@randomaccount" it works but its posting also the "\"
If i remove the "\" so it will not be posted the bot closes as soon as it opens and sends 0 comments.
Do you know how i can fix it?
In my config file the 6th line where i put the expression is 
"  Expression = \@account1 \@account2 "
Thanks in advance.

**Comment by Fytex** [comment]
I'm confused sry.
Expression = @@
Should evaluate to two _random_ mentions
If you want specific users you gotta add a \@user1 \@user2

Not sure if a space is needed between both @'s

**Comment by theodoroslam** [comment]
I want specific users so i altered the config file like this:
```
[Required]

	Post Link  = https://www.instagram.com/p/CLw7ambBoBE/
			# Post Link can be disabled (writing # before Post Link) only in case if Save Only is enabled and a User Target specified

	Expression = \@account1 \@account2
```
The problem is that when the bot sends the comment it sends also the "\" like you see in the atttched picture.
![Screenshot_1](https://user-images.githubusercontent.com/75037392/109823688-d51b0100-7c40-11eb-99da-f733cbcdd2ee.jpg)

**Comment by Fytex** [comment]
Updated it! I think its working properly but I didn't test it.
If you could give feedback about it.
Thanks :)

**Comment by theodoroslam** [comment]
Thank you is working properly.
Great script!
