### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by stelioskoul** [Fytex/Instagram-Giveaways-Winner#16]
Hello, i'm a mac user and i would like you to help me with this issue. When i run the script.py the following error shows in terminal: 

" from selenium import webdriver # type: ignore
ModuleNotFoundError: No module named 'selenium' "

Can you tell me what causes this problem?

**Comment by Fytex** [comment]
You didn't install selenium correctly.
Do `python -m pip install selenium` and then `python script.py` to run the script
Any more questionss join my discord server which is in my bio :)
