### ISSUE TITLE
Facebook linked account

### ISSUE THREAD

**Issue by bardas** [Fytex/Instagram-Giveaways-Winner#17]
how we can login into an account that was created from facebook account?

**Comment by Fytex** [comment]
The script doesn't implement a way to login with facebook. However, you can do a bypass.
1. Find out what is your Instagram Session Token and expiry (It's inside a cookie in your browser such as google chrome with the following domain: instagram.com)
2. Next to script.py create a folder called cookies
3. Create a file called {username}.json if your instagram name is bardas then bardas.json
4. Write `{"domain": ".instagram.com", "expiry": 1643379989.497126, "httpOnly": true, "name": "sessionid", "path": "/", "secure": true, "value": "0000000000000"}`
5.  Edit the expiry and value (the other ones are the same)
6. Save and run
