### ISSUE TITLE
HELP

### ISSUE THREAD

**Issue by Mauascm** [Fytex/Instagram-Giveaways-Winner#19]
it runs well, makes the first comment, but always on the second one instagram doesnt let the bot comment, and sometimes it crashes. :(

**Comment by Mauascm** [comment]
also the terminal leaves a message that says:

[27072:24876:0503/142947.313:ERROR:gpu_init.cc(426)] Passthrough is not supported, GL is disabled
Early termination. Sent 1 comments so far!

**Comment by Mauascm** [comment]
I found why instagram wasnt letting the bot comment. it was because it was trying to tag a person and that specific person dont let enyone tag him/her. is there a way to solve that?

**Comment by Fytex** [comment]
Sorry. We have already faced that problem before and from our research there is no way to find if that person is mentionable or not.

About the error you were getting `Passthrough is not supported, GL is disabled`. How did you solve?

**Comment by Mauascm** [comment]
Hi! I didn’t solve the pass through is not supported problem. But I think
it’s not bothering at all
