### ISSUE TITLE
Cannot comment after around 5 writes

### ISSUE THREAD

**Issue by fmchan** [Fytex/Instagram-Giveaways-Winner#2]
I think it's too fast. gotta set a time interval or sleep a while for each 2-3 comments left.

**Comment by Fytex** [comment]
I can add an configurable interval between each post but does that make a difference (maybe instagram allows more comments if you don't post so fast. I'll test it later) ?

**Comment by fmchan** [comment]
It can increase the number of comments if there is a random time interval between each comment because Instagram doesn't allow DDOS attacks or robotic actions.

**Comment by Fytex** [comment]
Thanks for your help. I'll try to find out a way to work on finding a nice interval between comments (they vary from user to user as I stated in README.md). And I'll do a login using cookies so Instagram doesn't take action because of too many logins.

**Comment by Fytex** [comment]
@fmchan Option added as you requested. In a future will try to make the script find the best interval between comments for your account. Thanks for your collaboration :)
