### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by Visualsuspect** [Fytex/Instagram-Giveaways-Winner#20]
USB: usb_device_handle_win.cc:1054 Failed to read descriptor from node connection: A device attached to the system is not functioning. (0x1F)

And i think because of that cant post a comment.

**Comment by Fytex** [comment]
https://github.com/Fytex/Instagram-Giveaways-Winner/blob/master/config.ini#L68


Try setting the Location in config.ini to your Google Chrome's location (don't forget to remove the '#' to enable it)

**Comment by Visualsuspect** [comment]
Nothing again. It says that starts the spamming but on the broswer that opens, it tries to make the comment and instagram pops up an error "could'nt post a comment" in the bottom of the broswer.

https://imgur.com/a/4SWSUHu

**Comment by Fytex** [comment]
Weird, that error doesn't seem mine.
Try updating the ChromeDriver to your respective Google's Chrome version. If you did that first then try going back by using the version I provided.
