### ISSUE TITLE
Stack at Logging in...

### ISSUE THREAD

**Issue by ggloveswp** [Fytex/Instagram-Giveaways-Winner#21]
Seems like I never received a confirmed successful log in message.

Any ideas?

![image](https://user-images.githubusercontent.com/18418930/117268622-283b4b00-ae60-11eb-8b03-f6ad09621326.png)

**Comment by Fytex** [comment]
Try disabling the option `Window` in config.ini (by adding a '#' before) or set it back to True. So you can see what's happening.
Next time post the whole error (you cutting the right side).

**Comment by ggloveswp** [comment]
It worked - thanks.
Last question please: Can i tag only specific accounts without searching the follwers of another account? 
Is this achiveable by creating a records/custom.txt that includes one account (including @) per line?

**Comment by Fytex** [comment]
Yes. However you will need to copy and paste those lines multiple times in your custom file if you want to mention them multiple times.
It works as a generator. If your comment needs three mentions then it picks the first three lines of users. Next time it picks from 4, 5 and 6 lines and so on.
You don't really need to call it `custom.txt`. As long as you edit and enable `Specific File`'s option in config.ini.

Glad it worked :)
