### ISSUE TITLE
Emoji doesn't work

### ISSUE THREAD

**Issue by fmchan** [Fytex/Instagram-Giveaways-Winner#3]
comment with emoji throws an error
selenium.common.exceptions.WebDriverException: Message: unknown error: ChromeDriver only supports characters in the BMP

**Comment by andreubita** [comment]
@Fytex please fix, i have the same error

**Comment by Fytex** [comment]
In reality this is not my problem. Its actually ChromeDriver's problem to not support other type of characters. 
One solution would be me making it for Firefox (Which will do in a future). 
The other would be using javascript to execute code in the browser (to write a comment with emoji) - (Which is probably the one I will try to find out)

You can always choose (smaller in terms of bits) emojis to work on that.

**Comment by Fytex** [comment]
@fmchan @andreubita Issue resolved (even though its not really my issue). Made some patches too (Hope there are no more bugs).

Thanks for your collaboration,
Fytex
